# Generated by Django 4.2.2 on 2023-06-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_author_id_alter_category_id_alter_comment_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(
                help_text="Please fill in a description of your specified category"
            ),
        ),
    ]
