# Generated by Django 4.2.2 on 2023-06-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_category_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(help_text="Max word count < 100 words"),
        ),
    ]
